### ISSUE TITLE
Long SSH commands are hard to see

### ISSUE THREAD

**Issue by luzlab** [StrictlySkyler/harbormaster#1]
I'm running commands like the following:

```
aws ec2 run-instances --image-id ami-4836a428 --count 1 --instance-type t2.micro --key-name <KEYPAIR> --security-group-ids sg-61132405 sg-0765df7c sg-9aa626e3 --subnet-id subnet-966c35e1 --region us-west-2 --user-data "`cat cloudinit-harbormaster.yaml`" --tag-specifications 'ResourceType=instance,Tags=[{Key=application,Value=devops},{Key=Name,Value=Harbormaster}]' --iam-instance-profile 'Name=DevOps'
```

Can we text box for the command dynamically increase in size to make it easier to work with long commands?

**Comment by StrictlySkyler** [comment]
Sure; this kind of customization is totally appropriate discussion for the harbor itself, here:
https://github.com/StrictlySkyler/harbormaster-ssh

Would you mind if we moved the discussion there?
