### ISSUE TITLE
Rendering the appearance of the harbor names 

### ISSUE THREAD

**Issue by luzlab** [StrictlySkyler/harbormaster#2]
Right now harbormaster just displays a text string of the harbor name.

![screen shot 2017-04-28 at 3 36 05 pm](https://cloud.githubusercontent.com/assets/9924835/25549726/6fd353ea-2c28-11e7-86bc-a328662f709c.png)

What do you think adding `.render_title()` so that the harbor can provide html instead? I'm thinking about adding a config button (tiny cogwheel) to setup harbor-wide parameters.

**Comment by StrictlySkyler** [comment]
These are each `<button>`s, and their name is governed by the name registered by the `.register()` method passed to your harbor on startup.

For custom UI/html, you should be able to make whatever you want by returning valid html from within the `render_input` method.

This is covered in the forthcoming documentation, so stay tuned.
